// <auto-generated />
using Cf.Dotnet.EntityFramework.Parte5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cf.Dotnet.EntityFramework.Parte5.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cf.Dotnet.EntityFramework.Parte5.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 777235512,
                            Name = "neural",
                            Price = 0.4348467837971520m
                        },
                        new
                        {
                            Id = 2121178650,
                            Name = "Bedfordshire",
                            Price = 0.08117704624213320m
                        },
                        new
                        {
                            Id = 1854948403,
                            Name = "Analyst",
                            Price = 0.6552809700941160m
                        },
                        new
                        {
                            Id = 1627690230,
                            Name = "Principal",
                            Price = 0.9403404901620640m
                        },
                        new
                        {
                            Id = 62202779,
                            Name = "indigo",
                            Price = 0.7406917764239440m
                        },
                        new
                        {
                            Id = 1999405661,
                            Name = "COM",
                            Price = 0.1301395832384160m
                        },
                        new
                        {
                            Id = 403144518,
                            Name = "navigate",
                            Price = 0.7480105917249670m
                        },
                        new
                        {
                            Id = 170307152,
                            Name = "Team-oriented",
                            Price = 0.4110946162612770m
                        },
                        new
                        {
                            Id = 1527132064,
                            Name = "interface",
                            Price = 0.03759202886896360m
                        },
                        new
                        {
                            Id = 1035187876,
                            Name = "Rand",
                            Price = 0.3187806442828970m
                        });
                });

            modelBuilder.Entity("Cf.Dotnet.EntityFramework.Parte5.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1784559130,
                            Name = "recontextualize"
                        },
                        new
                        {
                            Id = 269531841,
                            Name = "Handmade Granite Chair"
                        },
                        new
                        {
                            Id = 1250048129,
                            Name = "circuit"
                        },
                        new
                        {
                            Id = 1548625142,
                            Name = "pink"
                        },
                        new
                        {
                            Id = 1777755962,
                            Name = "copying"
                        },
                        new
                        {
                            Id = 1600760419,
                            Name = "withdrawal"
                        },
                        new
                        {
                            Id = 1400559217,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 1989899502,
                            Name = "purple"
                        },
                        new
                        {
                            Id = 2113317830,
                            Name = "GB"
                        },
                        new
                        {
                            Id = 1440246757,
                            Name = "Awesome"
                        });
                });

            modelBuilder.Entity("Cf.Dotnet.EntityFramework.Parte5.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1110588061,
                            CatalogItemId = 403144518,
                            CustomerId = 1400559217,
                            Quantity = 1692508996
                        },
                        new
                        {
                            Id = 118231333,
                            CatalogItemId = 170307152,
                            CustomerId = 1989899502,
                            Quantity = -1703387782
                        },
                        new
                        {
                            Id = 106842929,
                            CatalogItemId = 170307152,
                            CustomerId = 1400559217,
                            Quantity = 481663073
                        },
                        new
                        {
                            Id = 1661277252,
                            CatalogItemId = 1999405661,
                            CustomerId = 1777755962,
                            Quantity = 52140459
                        },
                        new
                        {
                            Id = 1980459864,
                            CatalogItemId = 1999405661,
                            CustomerId = 1400559217,
                            Quantity = 1741749428
                        },
                        new
                        {
                            Id = 539681038,
                            CatalogItemId = 1999405661,
                            CustomerId = 1400559217,
                            Quantity = 658515941
                        },
                        new
                        {
                            Id = 977156273,
                            CatalogItemId = 1627690230,
                            CustomerId = 1777755962,
                            Quantity = 57636514
                        },
                        new
                        {
                            Id = 1689251316,
                            CatalogItemId = 2121178650,
                            CustomerId = 1250048129,
                            Quantity = 2129188673
                        },
                        new
                        {
                            Id = 455695385,
                            CatalogItemId = 403144518,
                            CustomerId = 1600760419,
                            Quantity = -934525895
                        },
                        new
                        {
                            Id = 503200746,
                            CatalogItemId = 777235512,
                            CustomerId = 1989899502,
                            Quantity = 909388729
                        });
                });

            modelBuilder.Entity("Cf.Dotnet.EntityFramework.Parte5.Models.Order", b =>
                {
                    b.HasOne("Cf.Dotnet.EntityFramework.Parte5.Models.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cf.Dotnet.EntityFramework.Parte5.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cf.Dotnet.EntityFramework.Parte5.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
